theme: jekyll-theme-minimal
title: ["Discursos de Navidad: 1937-2018"]
description: ["Visualizaciones y comparativas de frecuencia sobre los discursos de Navidad de Franco, Juan Carlos I y Felipe VI."]
